### ISSUE TITLE
SMTP Password Longer than 24 Characters

### ISSUE THREAD

**Issue by emmaroland32** [konfer-be/cliam#12]
I get an error when using SMTP Password Longer than 24 characters

`Error in .cliamrc.json: "mode.smtp.password" length must be less than or equal to 24 characters long`

Some SMTP providers no longer allow setting of password rather a  long UUID characters is generated automatically when resetting password such as Mailgun.

Is it possibe to increase this SMTP Password Field to about lets say 64 characters.

Thanks

**Comment by steve-lebleu** [comment]
Hi @emmaroland32,

64 is quite long. I mean, we can say from 16 it's already secure. So in my opinion 64 is too much I think. The goal is not to let a door to push unexptected instructions. I let 24 from now. If there in practice this parameter is a bottleneck, I'll adapt if required.
