### ISSUE TITLE
Typescript typings available?

### ISSUE THREAD

**Issue by manwithsteelnerves** [konfer-be/cliam#3]
I recently came across this project and it perfectly fits my requirements. 
It's very well written and a great job done! Thanks for sharing it!

I started integrating and found typings are missing. Is there a possibility to add those?

**Comment by steve-lebleu** [comment]
It should be great, yes. I will do that ASAP with the next enhancements. Stay tunned !

**Comment by steve-lebleu** [comment]
This is done in v1.0.15, you can upgrade your package to have typings available.

**Comment by manwithsteelnerves** [comment]
Great! Thanks for adding!
